
INSERT into CityZip (zipcode, city) VALUES ('9000', 'Aalborg')
INSERT into _Address (street, house_no, city_zipcode) VALUES ('Nørregade', '3', '9000')
INSERT into _Address (street, house_no, city_zipcode) VALUES ('Kirsebærvej', '2', '9000')
INSERT into Person (f_name, l_name, email, phone_no, person_type, address_id) VALUES ('Karsten', 'Jensen', 'kj@mail.com','29384726', '1', 1)
INSERT into Person (f_name, l_name, email, phone_no, person_type, address_id) VALUES ('Gitte', 'Poulsen', 'gp@badminton.com','37485928', '0', 2)
INSERT into Court (id, hall_no) VALUES (1, 1)
INSERT into Court (id, hall_no) VALUES (2, 1)
INSERT into Court (id, hall_no) VALUES (3, 1)
INSERT into Court (id, hall_no) VALUES (4, 2)
INSERT into Court (id, hall_no) VALUES (5, 2)
INSERT into Court (id, hall_no) VALUES (6, 2)
INSERT into Court (id, hall_no) VALUES (7, 3)
INSERT into Court (id, hall_no) VALUES (8, 3)
INSERT into Court (id, hall_no) VALUES (9, 3)
INSERT into Reservation (date_time, is_equipment, from_time, court_id, customer_id, employee_id) VALUES ('2022-02-03', 1, '13:00:00', 1, 1, NULL)
INSERT into Invoice (total_price, reservation_id) VALUES (150, 1)

INSERT into CityZip (zipcode, city) VALUES ('8000', 'Aarhus')
INSERT into _Address (street, house_no, city_zipcode) VALUES ('Østerbro', '4', '8000')
INSERT into Person (f_name, l_name, email, phone_no, person_type, address_id) VALUES ('Birgit', 'Hansen', 'bh@mail.com','28374950', '1', 2)
INSERT into Reservation (date_time, is_equipment, from_time, court_id, customer_id, employee_id) VALUES ('2022-02-04', 1, '15:00:00', 2, 2, 1)
INSERT into Invoice (total_price, reservation_id) VALUES (200, 2)